In [1]:
import numpy as np

<module 'numpy.version' from 'c:\\Users\\hallgato\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\version.py'>


In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [ ]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tuple-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

In [9]:
def create_array(size:tuple=(2,2))->list:
    return np.zeros(size,dtype=int)

array([[0, 0],
       [0, 0]])

In [ ]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlóját feltölti egyesekkel
#Be: [[1,2],[3,4]]
#Ki: [[1,2],[3,1]]
#set_one()

In [33]:
def set_one(inputArray:np.array)->np.array:
    np.fill_diagonal(inputArray,1)
    return inputArray

None


In [ ]:
# Készíts egy függvényt ami transzponálja a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 2], [3, 4]]
# do_transpose()

In [32]:
def do_transpose(inputArray:np.array)->np.array:
    return np.transpose(inputArray)

array([[1, 3],
       [2, 4]])

In [ ]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, ha nincs megadva ez a paraméter, akkor legyen az alapértelmezett a kettő 
# Be: [0.1223, 0.1675], 2
# Ki: [0.12, 0.17]
# round_array()

In [37]:
def round_array(inputArray:np.array,roundTo:int=2)->np.array:
    return np.around(inputArray,roundTo)

array([0.12, 0.17])

In [ ]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 0 - False-ra, az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

In [38]:
def bool_array(inputArray:np.array)->np.array:
    return np.array(inputArray,dtype=bool)

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# invert_bool_array()

In [39]:
def invert_bool_array(inputArray:np.array)->np.array:
    return np.invert(
        np.array(inputArray,dtype=bool))

array([[False,  True,  True],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()


In [40]:
def flatten(inputArray:np.array)->np.array:
    return np.ndarray.flatten(inputArray)

array([1, 2, 3, 4])