In [1]:
import numpy as np

In [3]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [4]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait. Bemenetként egy array-t vár.
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

In [5]:
def column_swap(inputArray:np.array)->np.array:
    temp=np.copy(inputArray[:,0])
    inputArray[:,0]=inputArray[:,1]
    inputArray[:,1]=temp
    return inputArray

In [6]:
# Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

In [7]:
def compare_two_array(inputArray1:np.array,inputArray2:np.array)->np.array:
    return np.where(np.equal(inputArray1,inputArray2))


In [8]:
# Készíts egy olyan függvényt, ami vissza adja string-ként a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!, 

In [9]:
def get_array_shape(inputArray:np.array)->str:
   output=""
   a=np.shape(inputArray)
   if (len(a)==2):
      output+=f"sor: {a[0]}, oszlop: {a[1]}, melyseg: 1"
   else:
      output+=f"sor: {a[0]}, oszlop: {a[1]}, melyseg: {a[2]}"

   return output

In [10]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges pred-et egy numpy array-ből. 
# Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli. 
# Pl. ha 1 van a bemeneten és 4 classod van, akkor az adott sorban az array-ban a [1] helyen álljon egy 1-es, a többi helyen pedig 0.
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

In [3]:
def encode_Y(InputArray:np.array,classCount:int)->np.array:
    zeroMatrix = np.zeros((len(InputArray),classCount),dtype=int)
    zeroMatrix[np.arange(len(InputArray)),InputArray]=1
    return zeroMatrix

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1]])

In [ ]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()

In [5]:
def decode_Y(inputArray:np.array)->np.array:
    return np.argmax(inputArray,axis=1)

array([1, 2, 0, 3], dtype=int64)

In [ ]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenetként egy listát és egy array-t és adja vissza azt az elemet, aminek a legnagyobb a valószínüsége(értéke) a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. # Az ['alma', 'körte', 'szilva'] egy lista!
# Ki: 'szilva'
# eval_classification()

In [ ]:
def eval_classification(itemList:list,inputArray:np.array)->str:
    index=np.where(inputArray==np.max(inputArray))
    return itemList[index[0][0]]

'szilva'

In [ ]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# repalce_odd_numbers()

In [ ]:
def repalce_odd_numbers(inputArray:np.array)->np.array:
    inputArray[(inputArray%2!=0)]=-1
    return inputArray

array([-1,  2, -1,  4, -1,  6])

In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

In [ ]:
def replace_by_value(inputArray:np.array,compareValue:int)->np.array:
    inputArray[(inputArray<compareValue)]=-1
    inputArray[(inputArray>=compareValue)]=1
    return inputArray

array([-1,  1,  1, -1])

In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit összeszorozza és az eredményt visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

In [ ]:
def array_multi(inputArray:np.array):
    return np.prod(inputArray)

24

In [ ]:
# Készíts egy olyan függvényt, ami egy 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

In [ ]:
def array_multi_2d(inputArray:np.array)->np.array:
    return np.multiply.reduce(inputArray,axis=1)

array([ 2, 12])

In [ ]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()


In [12]:
def add_border(inputArray:np.array)->np.array:
    return np.pad(inputArray,pad_width=1,mode='constant',constant_values=0)

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [ ]:
# A KÖTVETKEZŐ FELADATOKHOZ NÉZZÉTEK MEG A NUMPY DATA TYPE-JÁT!

In [ ]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot és ezt adja vissza egy numpy array-ben. A fgv ként str vár paraméterként 'YYYY-MM' formában.
# Be: '2023-03', '2023-04'  # mind a kettő paraméter str.
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()

In [9]:
def list_days(startDate:str,endDate:str)->np.array:
    return np.array(np.arange(startDate+'-01',endDate+'-01',dtype=np.datetime64))

array(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
       '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
       '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
       '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
       '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
       '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
       '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28'],
      dtype='datetime64[D]')

In [ ]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD. Térjen vissza egy 'numpy.datetime64' típussal.
# Be:
# Ki: 2017-03-24


In [14]:
def actual_date()->str:
    return np.datetime64('today')

numpy.datetime64('2023-03-10')

In [ ]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:02:00 óta. Int-el térjen vissza
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()

In [17]:
def sec_from_1970()->int:
    return np.datetime64('now','s') - np.datetime64('1970-01-01T00:02:00')